name: Update Lichess Stats
on:
  schedule:
    - cron: '1 20 * * *' # Запуск каждый день в 22:01 по Берлину
  workflow_dispatch: # Позволяет запустить вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run update script
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python update_data.py
      - name: Commit and push if changed
        run: |
          git config --global user.name 'StatsBot'
          git config --global user.email 'bot@github.com'
          git add index.html
          git commit -m "Auto-update stats" || exit 0
          git pull --rebase origin main
          git push
